import './globals.css';
import type { Metadata } from 'next';
import { ClerkProvider } from '@clerk/nextjs';
// Import the font loader
import { Inter } from 'next/font/google'; 
import { Toaster } from '@/components/ui/sonner';

// Configure the font
const googleSansLike = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Expense Tracker',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        cssLayerName: 'clerk',
      }}
    >
      <html lang="en">
        {/* Apply the font class to the body */}
        <body className={googleSansLike.className}>
          <Toaster/>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}